[package]
name = "emutream_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
