[package]
name = "gameboy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
rusty_boy_core = { path = "C://Users/trist/Desktop/Programmation/Rust/rusty_boy/core" }
console_error_panic_hook = "0.1.7"
